### ISSUE TITLE
iOS build instructions

### ISSUE THREAD

**Issue by drewwells** [thielepaul/photoprism-mobile#64]
I wanted to install this on my phone, but did not find any instructions on how to do so. So far, this is where I got.

Requirements cocoapod flutter
brew install cocoapod

For Flutter,
Checkout stable version of github.com/flutter/flutter. Execute flutter to do a dart based installation of the binary and dependencies
```
flutter
```

navigate to photoprism-mobile, run
flutter pub get

Now you should be able to build. At this point, you will need to do some iOS signing.
`flutter run`

I was not able to get this to install under org.photoprism.photoprism. I changed the bundle identifier and it built with a personal (non-paying) iOS account.

If this all works, you can now install the pod
`cd ios; pod install`

At this point, xCode could build the project but threw some errors. I'm guessing those are environment specific problems for me.

**Comment by thielepaul** [comment]
I think the steps for me were:
* install requirements: cocoapod, flutter & XCode
* checkout repository
* cd to repo and execute: `flutter pub get && cd ios && pod install && cd ..`
* open {repo}/ios/Runner.xcodeproj in XCode
* click the build and run button in XCode
* allow certificate on iPhone
* go to Runner > Edit Scheme in XCode and set the Build Configuration to Release instead of Debug
* build and run the app again

About my build environment:
hackintosh, iPhone 6, Flutter v1.17.4, on Mac OS X 10.15.3 19D76

Are you able to build and run a empty flutter app (generated via `flutter create testapp`)?

**Comment by thielepaul** [comment]
If you just want to test the app on your iPhone you can also use the following testflight link: https://testflight.apple.com/join/Rxzv6JpC
